-- Add new fields to bot_config table
ALTER TABLE bot_config 
ADD COLUMN IF NOT EXISTS rodape TEXT DEFAULT 'TV ON Sistema - Atendimento 24/7',
ADD COLUMN IF NOT EXISTS usar_botoes BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS detectar_novos_clientes BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS tempo_resposta INTEGER DEFAULT 30,
ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP DEFAULT NOW();